# Generated by Django 5.0.6 on 2024-07-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingrediente',
            old_name='ricette',
            new_name='ricetta',
        ),
        migrations.RenameField(
            model_name='ricetta',
            old_name='ristoranti',
            new_name='ristorante',
        ),
    ]
