# Generated by Django 5.0.6 on 2024-07-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_ricette_ingrediente_ricetta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='ricetta',
        ),
        migrations.AddField(
            model_name='ricetta',
            name='ingrediente',
            field=models.ManyToManyField(to='api.ingrediente'),
        ),
        migrations.AddField(
            model_name='ristorante',
            name='indirizzo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
